language: python
python:
  - "3.8"
services:
  - docker
before_install:
- docker pull rabbitmq
- docker pull mongo
- docker run -d -p 5672:5672 rabbitmq
- sudo docker run -d -p 27017:27017 mongo
- docker ps -a
install:
  - pip install -r requirements.txt
script:
  - pytest --cov-report term --cov=thinkpol
after_success:
  - codecov



script:
- bundle exec rake test
